version: 2

registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
    nuget-feed-version: V3

updates:

  - package-ecosystem: "nuget"
    directory: "/"
    targetFramework: net10.0
    target-branch: main
    versioning-strategy: increase
    reviewers:
      - "trejjam" # Jan Trejbal
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore"
      include: "scope" # Adds the dependency name to the commit message
    registries:
      - nuget
    groups:
      microsoft-dependencies:
        patterns:
          - "Microsoft.*"
          - "System.*"
      verify-dependencies:
        patterns:
          - "Verify"
          - "Verify.*"
      xunit-dependencies:
        patterns:
          - "xunit"
          - "xunit.*"
          - "MartinCostello.Logging.XUnit*"
      polly-dependencies:
        patterns:
          - "Polly.*"
          - "Polly"
      nuget-dependencies:
        patterns:
          - "NuGet.*"
      corvus-dependencies:
        patterns:
          - "Corvus.*"
      azure-dependencies:
        patterns:
          - "Azure.*"
      nsubstitute-dependencies:
        patterns:
          - "NSubstitute*"
    ignore:
      - dependency-name: "Microsoft.*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "System.*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "xunit.v3.*"
        update-types:
          - "version-update:semver-major"
